CREATE TABLE bonds.bonds_analysis AS
SELECT
  Date,
  EXTRACT(MONTH FROM CAST(Date AS DATE)) AS MONTH,
  EXTRACT(YEAR FROM CAST(Date AS DATE)) AS YEAR,
  AGG,
  LAG(AGG) OVER (ORDER BY Date) AS Previous_AGG,
  (AGG - LAG(AGG) OVER (ORDER BY Date)) / LAG(AGG) OVER (ORDER BY Date) * 100 AS AGG_Pct_Change,
  (AGG / FIRST_VALUE(AGG) OVER (ORDER BY Date) - 1) * 100 AS AGG_Cumulative_Return,
  BIL,
  LAG(BIL) OVER (ORDER BY Date) AS Previous_BIL,
  (BIL - LAG(BIL) OVER (ORDER BY Date)) / LAG(BIL) OVER (ORDER BY Date) * 100 AS BIL_Pct_Change,
  (BIL / FIRST_VALUE(BIL) OVER (ORDER BY Date) - 1) * 100 AS BIL_Pct_Cumulative_Return,
  BND,
  LAG(BND) OVER (ORDER BY Date) AS Previous_BND,
  (BND - LAG(BND) OVER (ORDER BY Date)) / LAG(BND) OVER (ORDER BY Date) * 100 AS BND_Pct_Change,
  (BND / FIRST_VALUE(BND) OVER (ORDER BY Date) - 1) * 100 AS BND_Pct_Cumulative_Return,
  EDV,
  LAG(EDV) OVER (ORDER BY Date) AS Previous_EDV,
  (EDV - LAG(EDV) OVER (ORDER BY Date)) / LAG(EDV) OVER (ORDER BY Date) * 100 AS EDV_Pct_Change,
  (EDV / FIRST_VALUE(EDV) OVER (ORDER BY Date) - 1) * 100 AS EDV_Pct_Cumulative_Return,
  IEF,
  LAG(IEF) OVER (ORDER BY Date) AS Previous_IEF,
  (IEF - LAG(IEF) OVER (ORDER BY Date)) / LAG(IEF) OVER (ORDER BY Date) * 100 AS IEF_Pct_Change,
  (IEF / FIRST_VALUE(IEF) OVER (ORDER BY Date) - 1) * 100 AS IEF_Pct_Cumulative_Return,
  SGOV,
  LAG(SGOV) OVER (ORDER BY Date) AS Previous_SGOV,
  (SGOV - LAG(SGOV) OVER (ORDER BY Date)) / LAG(SGOV) OVER (ORDER BY Date) * 100 AS SGOV_Pct_Change,
  (SGOV / FIRST_VALUE(SGOV) OVER (ORDER BY Date) - 1) * 100 AS SGOV_Pct_Cumulative_Return,
  SHV,
  LAG(SHV) OVER (ORDER BY Date) AS Previous_SHV,
  (SHV - LAG(SHV) OVER (ORDER BY Date)) / LAG(SHV) OVER (ORDER BY Date) * 100 AS SHV_Pct_Change,
  (SHV / FIRST_VALUE(SHV) OVER (ORDER BY Date) - 1) * 100 AS SHV_Pct_Cumulative_Return,
  SHY,
  LAG(SHY) OVER (ORDER BY Date) AS Previous_SHY,
  (SHY - LAG(SHY) OVER (ORDER BY Date)) / LAG(SHY) OVER (ORDER BY Date) * 100 AS SHY_Pct_Change,
  (SHY / FIRST_VALUE(SHY) OVER (ORDER BY Date) - 1) * 100 AS SHY_Pct_Cumulative_Return,
  TLH,
  LAG(TLH) OVER (ORDER BY Date) AS Previous_TLH,
  (TLH - LAG(TLH) OVER (ORDER BY Date)) / LAG(TLH) OVER (ORDER BY Date) * 100 AS TLH_Pct_Change,
  (TLH / FIRST_VALUE(TLH) OVER (ORDER BY Date) - 1) * 100 AS TLH_Pct_Cumulative_Return,
  TLT,
  LAG(TLT) OVER (ORDER BY Date) AS Previous_TLT,
  (TLT - LAG(TLT) OVER (ORDER BY Date)) / LAG(TLT) OVER (ORDER BY Date) * 100 AS TLT_Pct_Change,
  (TLT / FIRST_VALUE(TLT) OVER (ORDER BY Date) - 1) * 100 AS TLT_Pct_Cumulative_Return,
  VGIT,
  LAG(VGIT) OVER (ORDER BY Date) AS Previous_VGIT,
  (VGIT - LAG(VGIT) OVER (ORDER BY Date)) / LAG(VGIT) OVER (ORDER BY Date) * 100 AS VGIT_Pct_Change,
  (VGIT / FIRST_VALUE(VGIT) OVER (ORDER BY Date) - 1) * 100 AS VGIT_Pct_Cumulative_Return
FROM
  bonds